version: "3"

services:

  gnbt:
    image: lpoaura/gnbt:dev
    container_name: gnbt
    ports:
      - $APP_PORT:8080
    volumes:
      - $APP_DIR/config:/config
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT