version: "3"

services:
  redis:
    image: redis:latest
    container_name: gnbt_redis
    volumes:
      - gnbt_cachedb_vol:/data
    networks:
      - _net_gnbt

  gnbt:
    image: lpoaura/gnbt:dev
    container_name: gnbt_app
    env_file:
      - .env
    volumes:
      - gnbt_app_custom_vol:/app/app/static/custom/assets
    ports:
      - 8080:8080
    networks:
      - _net_gnbt
    depends_on:
      - "redis"


volumes:
  gnbt_app_custom_vol:
  gnbt_cachedb_vol:

networks:
  _net_gnbt: