version: "3"

services:

  gnbt:
    image: lpoaura/gnbt:dev
    container_name: gnbt
#    volumes:
#      - /opt/docker/gnbt/config:/config
    ports:
      - 86:8080
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
#    labels:
#      - traefik.http.routers.gnbt.rule=Host(`gnbt.lefrezas.net`)
#      - traefik.http.services.gnbt.loadbalancer.server.port=8080
#      - traefik.http.routers.gnbt.tls.certresolver=le
#      - traefik.http.routers.gnbt.entrypoints=web-secure
#      - traefik.http.middlewares.gnbt.redirectscheme.scheme=https
#      - traefik.http.middlewares.gnbt.redirectscheme.permanent=true
#      - traefik.http.middlewares.gnbt.compress=true

#networks:
#  default:
#    external:
#      name: front
