[tool.poetry]
name = "GeoNature-biodiv-territoires"
version = "0.1.0"
description = "Porté à connaissance de la biodiversité des territoires"
authors = ["lpofredc <frederic.cloitre@lpo.fr>"]
license = "AGPL-3.0-or-later"
packages = [
    { include = "app" },
    { include = "wsgi.py"},
]

[tool.poetry.scripts]
start = 'wsgi:app'

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"
Flask-SQLAlchemy = "^2.5.1"
Flask-Admin = "^1.5.7"
psycopg2-binary = "^2.8.6"
GeoAlchemy2 = "^0.8.4"
pypnnomenclature = {url = "https://github.com/PnX-SI/Nomenclature-api-module/archive/1.3.6.zip"}
Shapely = "^1.7.1"
Flask-Assets = "^2.0"
Flask-CKEditor = "^0.4.4"
geojson = "^2.5.0"
utils-flask-sqlalchemy = "^0.1.4"
utils-flask-sqlalchemy-geo = "^0.1.3"

[tool.poetry.dev-dependencies]
coloredlogs = "^15.0"
black = "^20.8b1"
mypy = "^0.812"
flake8 = "^3.9.0"
isort = "^5.8.0"
pylint = "^2.7.2"
Flask-MonitoringDashboard = "^3.1.0"


[tool.isort]
include_trailing_comma = true
line_length = 79
multi_line_output = 3

[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
include = '\.pyi?$'
line-length = 79
target-version = ['py37']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
